### ISSUE TITLE
[Feature Request] Open the chapter in the specific extension website instead of the program

### ISSUE THREAD

**Issue by duradara** [Suwayomi/Suwayomi-WebUI#558]
## What feature should be added to Suwayomi?
I would like it if you could add an option to open a manga chapter in the specific extension website instead of the program.  Currently you can only go to their site by clicking the "open site" button then go and click the chapter.
Example: I click chapter 40 of some manga and instead of opening the in-program reader it opens the chapter in the translators website
##  Why/Project's Benefit/Existing Problem
Becase it would allow us to support translators by using their site.

-Sorry if my english is bad and you cant understand me.

**Comment by Robonau** [comment]
@Syer10 this would need support on the server first for it to be implemented in a client (not that i think it should be)

@duradara it opens in a Suwayomi UI because Suwayomi still needs to control the page, if it were to open in the sources page Suwayomi wouldn't be able to track your reading status automatically or give you any options in chaining how the reader functions, basically removing the whole point of Suwayomi

if you want to do this then itl be less clicks to just go through the "open site" button

**Comment by Syer10** [comment]
The server provides the chapter realUrl @Robonau
