### ISSUE TITLE
[Bug] Certain reading modes will try to load all pages

### ISSUE THREAD

**Issue by Secozzi** [Suwayomi/Suwayomi-WebUI#623]
## Device information
- Suwayomi version: v1.0.0-r1498-linux-x64, WebUI preview r1412
- Server Operating System: EndeavourOS Linux x86_64 6.7.5-arch1-1
- Server Desktop Environment: Plasma 5.27.10
- Server JVM version: openjdk version "21.0.2" 2024-01-16
- Client Operating System: same as above Server Operating System
- Client Web Browser: LibreWolf 122.0.1-2

## Steps to reproduce
1. Set reader type to either double page, webtoon, continuous vertical, or horizontal 
2. Click on a chapter

### Expected behavior
Just like single page, only the current page should load. For double page for example, at most one more page should be loaded.

### Actual behavior
Tachidesk will try to load all of the pages. This is a problem for servers that can't handle the load. If the chapter contains hundreds of pages, stuff like rate-limiting in the extension may not help. It will also continue to load all of the pages even after exiting the reader.

**Comment by schroda** [comment]
the browser only does ~6 request to the same origin in parallel, the rest of the requests are pending, so the server doesn't know that the client is currently trying to load more than 6 pages
the problem is that on client side these pending requests aren't getting aborted, thus, they're blocking all future requests
so aborting them once the reader gets closed or the chapter changes will prevent this issue

not preloading the pages will just result in a poor experience for slow sources as can already be seen with the single page mode for uncached and not downloaded chapters

however, the overall page request logic is something that can be improved in the future but for now aborting the requests is the easier fix and is something that should happen regardless of if pages are getting preloaded or not
